### ISSUE TITLE
Possible to upgrade to latest numpy?

### ISSUE THREAD

**Issue by jwhite007** [pdxgx/neoepiscope#14]
Neoepiscope requires a very outdated version of numpy (1.14.5). Is it possible to update to use the latest (1.18.4)? Thanks.

**Comment by maryawood** [comment]
Thanks for pointing out this issue! We have eliminated the outdated numpy requirement, and have generated a new release of neoepisope (v0.3.9). Hope this helps!

**Comment by jwhite007** [comment]
@maryawood,

Thank you so much. That was quick. I saw that v0.3.9 was already available in PyPI as soon as I noticed your reply. I'm a bit confused, however. I guess numpy was never even needed in the latest versions of neoepiscope. I can't find reference to it in any of the code.

**Comment by maryawood** [comment]
Yes, sorry for not explaining - requiring that version of numpy was a workaround for some versioning issues with other required tools, rather than a necessity for neoepiscope itself, but that workaround is no longer needed based on updates to those tools. It was a relic we didn't need anymore, so thank you for pointing it out!
